CREATE TABLE tbl_books (
    B_CODE	    VARCHAR2(6)	    NOT NULL	PRIMARY KEY,
    B_NAME	    nVARCHAR2(125)	NOT NULL,
    B_AUTHER	nVARCHAR2(125)	NOT NULL,
    B_COMP	    nVARCHAR2(125),
    B_YEAR	    NUMBER	NOT NULL,
    B_IPRICE	NUMBER,
    B_RPRICE	NUMBER	NOT NULL
);

CREATE TABLE tbl_users (
    U_CODE	VARCHAR2(6)	    NOT NULL	PRIMARY KEY,
    U_NAME	nVARCHAR2(125)	NOT NULL,
    U_TEL	nVARCHAR2(125),
    U_ADDR	nVARCHAR2(125)		
);

CREATE TABLE tbl_rent_book (
    RENT_SEQ	        NUMBER	        NOT NULL	PRIMARY KEY,
    RENT_DATE	        VARCHAR2(10)	NOT NULL,
    RENT_RETURN_DATE	VARCHAR2(10)	NOT NULL,
    RENT_BCODE	        VARCHAR2(6)	    NOT NULL,
    RENT_UCODE	        VARCHAR2(6)	    NOT NULL,
    RENT_RETUR_YN	    VARCHAR2(1),
    RENT_POINT	        NUMBER
);

SELECT * FROM tbl_books;
SELECT COUNT(*) FROM tbl_books;

SELECT * FROM tbl_users;
SELECT COUNT(*)  FROM tbl_users;

ALTER TABLE tbl_rent_book
ADD CONSTRAINT FK_BOOKS
FOREIGN KEY(RENT_BCODE)
REFERENCES tbl_books(B_CODE);

ALTER TABLE tbl_rent_book
ADD CONSTRAINT FK_USERS
FOREIGN KEY(RENT_UCODE)
REFERENCES tbl_users(U_CODE);

CREATE SEQUENCE SEQ_RENT
START WITH 1 INCREMENT BY 1;

SELECT * FROM tbl_books ORDER BY b_code DESC ;


CREATE VIEW view_rent AS
(
    SELECT
        RB.RENT_SEQ,
        RB.RENT_DATE,
        RB.RENT_RETURN_DATE,
        B.B_CODE,
        B.B_NAME,	
        U.U_CODE,
        U.U_NAME,
        RB.RENT_RETUR_YN
    FROM tbl_rent_book RB
        LEFT JOIN tbl_books B
            ON RB.RENT_BCODE = B.B_CODE
        LEFT JOIN tbl_users U
            ON RB.RENT_UCODE = U.U_CODE
);

SELECT * FROM view_rent;

SELECT * FROM tbl_rent_book
WHERE RENT_BCODE = RENT_BCODE AND RENT_RETUR_YN IS NULL;
